pipeline:
  test:
    image: ruby:2.5
    commands:
      - bundle install
      - bundle exec rspec
      - ./bin/flying-shuttle -h
  docker:
    registry: quay.io
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: quay.io/kontena/weave-flying-shuttle
    dockerfile: Dockerfile
    auto_tag: true
    when:
      branches: ['master', 'refs/tags/*']